# Generated by Django 4.2 on 2023-07-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile/avatar/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='taxpayer',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ИНН'),
        ),
    ]
