# Generated by Django 4.2 on 2023-07-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_moderated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
